# Generated by Django 2.2.10 on 2020-04-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0003_auto_20200331_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplodato',
            options={},
        ),
    ]
