# Generated by Django 2.2.10 on 2020-04-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_auto_20200401_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplodato',
            options={'managed': False},
        ),
    ]
