# Generated by Django 2.2.10 on 2020-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplodato',
            name='latitud',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='ejemplodato',
            name='longitud',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
