<<<<<<< HEAD
# Generated by Django 2.2.10 on 2020-03-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20200326_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplodato',
            options={'managed': False},
        ),
    ]
=======
# Generated by Django 2.2.10 on 2020-03-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20200326_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplodato',
            options={'managed': False},
        ),
    ]
>>>>>>> Desarollo
