# Generated by Django 2.2.10 on 2020-04-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0005_auto_20200401_1006'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ejemplodato',
            table='parkings',
        ),
    ]
